SOURCES += ClawPet/ClawSettings/DyberControlPanel.py \
        ClawPet/ClawSettings/BasicSettingUI.py \
        ClawPet/ClawSettings/CharCardUI.py \
        ClawPet/ClawSettings/GameSaveUI.py \
        ClawPet/ClawSettings/ItemCardUI.py \
        ClawPet/ClawSettings/custom_base.py \
        ClawPet/ClawSettings/custom_utils.py \
        ClawPet/Accessory.py \
        ClawPet/__init__.py \
        ClawPet/modules.py \
        ClawPet/extra_windows.py \
        ClawPet/Notification.py \
        ClawPet/Dashboard/DashboardUI.py \
        ClawPet/Dashboard/animationUI.py \
        ClawPet/Dashboard/buffModule.py \
        ClawPet/Dashboard/dashboard_widgets.py \
        ClawPet/Dashboard/inventoryUI.py \
        ClawPet/Dashboard/shopUI.py \
        ClawPet/Dashboard/statusUI.py \
        ClawPet/Dashboard/taskUI.py \
        ClawPet/Dashboard/animDesignUI.py \